# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BusinessBankAccount(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, bank_name: str=None, account_number: int=None, ifsc_code: str=None, account_type: str=None, primary_account: str=None, version: int=None):  # noqa: E501
        """BusinessBankAccount - a model defined in Swagger

        :param bank_name: The bank_name of this BusinessBankAccount.  # noqa: E501
        :type bank_name: str
        :param account_number: The account_number of this BusinessBankAccount.  # noqa: E501
        :type account_number: int
        :param ifsc_code: The ifsc_code of this BusinessBankAccount.  # noqa: E501
        :type ifsc_code: str
        :param account_type: The account_type of this BusinessBankAccount.  # noqa: E501
        :type account_type: str
        :param primary_account: The primary_account of this BusinessBankAccount.  # noqa: E501
        :type primary_account: str
        :param version: The version of this BusinessBankAccount.  # noqa: E501
        :type version: int
        """
        self.swagger_types = {
            'bank_name': str,
            'account_number': int,
            'ifsc_code': str,
            'account_type': str,
            'primary_account': str,
            'version': int
        }

        self.attribute_map = {
            'bank_name': 'bank_name',
            'account_number': 'account_number',
            'ifsc_code': 'ifsc_code',
            'account_type': 'account_type',
            'primary_account': 'primary_account',
            'version': 'version'
        }

        self._bank_name = bank_name
        self._account_number = account_number
        self._ifsc_code = ifsc_code
        self._account_type = account_type
        self._primary_account = primary_account
        self._version = version

    @classmethod
    def from_dict(cls, dikt) -> 'BusinessBankAccount':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BusinessBankAccount of this BusinessBankAccount.  # noqa: E501
        :rtype: BusinessBankAccount
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bank_name(self) -> str:
        """Gets the bank_name of this BusinessBankAccount.


        :return: The bank_name of this BusinessBankAccount.
        :rtype: str
        """
        return self._bank_name

    @bank_name.setter
    def bank_name(self, bank_name: str):
        """Sets the bank_name of this BusinessBankAccount.


        :param bank_name: The bank_name of this BusinessBankAccount.
        :type bank_name: str
        """
        if bank_name is None:
            raise ValueError("Invalid value for `bank_name`, must not be `None`")  # noqa: E501

        self._bank_name = bank_name

    @property
    def account_number(self) -> int:
        """Gets the account_number of this BusinessBankAccount.


        :return: The account_number of this BusinessBankAccount.
        :rtype: int
        """
        return self._account_number

    @account_number.setter
    def account_number(self, account_number: int):
        """Sets the account_number of this BusinessBankAccount.


        :param account_number: The account_number of this BusinessBankAccount.
        :type account_number: int
        """
        if account_number is None:
            raise ValueError("Invalid value for `account_number`, must not be `None`")  # noqa: E501

        self._account_number = account_number

    @property
    def ifsc_code(self) -> str:
        """Gets the ifsc_code of this BusinessBankAccount.


        :return: The ifsc_code of this BusinessBankAccount.
        :rtype: str
        """
        return self._ifsc_code

    @ifsc_code.setter
    def ifsc_code(self, ifsc_code: str):
        """Sets the ifsc_code of this BusinessBankAccount.


        :param ifsc_code: The ifsc_code of this BusinessBankAccount.
        :type ifsc_code: str
        """
        if ifsc_code is None:
            raise ValueError("Invalid value for `ifsc_code`, must not be `None`")  # noqa: E501

        self._ifsc_code = ifsc_code

    @property
    def account_type(self) -> str:
        """Gets the account_type of this BusinessBankAccount.


        :return: The account_type of this BusinessBankAccount.
        :rtype: str
        """
        return self._account_type

    @account_type.setter
    def account_type(self, account_type: str):
        """Sets the account_type of this BusinessBankAccount.


        :param account_type: The account_type of this BusinessBankAccount.
        :type account_type: str
        """
        allowed_values = ["Y", "N"]  # noqa: E501
        if account_type not in allowed_values:
            raise ValueError(
                "Invalid value for `account_type` ({0}), must be one of {1}"
                .format(account_type, allowed_values)
            )

        self._account_type = account_type

    @property
    def primary_account(self) -> str:
        """Gets the primary_account of this BusinessBankAccount.


        :return: The primary_account of this BusinessBankAccount.
        :rtype: str
        """
        return self._primary_account

    @primary_account.setter
    def primary_account(self, primary_account: str):
        """Sets the primary_account of this BusinessBankAccount.


        :param primary_account: The primary_account of this BusinessBankAccount.
        :type primary_account: str
        """
        allowed_values = ["Y", "N"]  # noqa: E501
        if primary_account not in allowed_values:
            raise ValueError(
                "Invalid value for `primary_account` ({0}), must be one of {1}"
                .format(primary_account, allowed_values)
            )

        self._primary_account = primary_account

    @property
    def version(self) -> int:
        """Gets the version of this BusinessBankAccount.


        :return: The version of this BusinessBankAccount.
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version: int):
        """Sets the version of this BusinessBankAccount.


        :param version: The version of this BusinessBankAccount.
        :type version: int
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version
