# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.business_platform_details import BusinessPlatformDetails  # noqa: F401,E501
from swagger_server import util


class BusinessPlatformDetailsObject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, business_platform_details: BusinessPlatformDetails=None):  # noqa: E501
        """BusinessPlatformDetailsObject - a model defined in Swagger

        :param business_platform_details: The business_platform_details of this BusinessPlatformDetailsObject.  # noqa: E501
        :type business_platform_details: BusinessPlatformDetails
        """
        self.swagger_types = {
            'business_platform_details': BusinessPlatformDetails
        }

        self.attribute_map = {
            'business_platform_details': 'businessPlatformDetails'
        }

        self._business_platform_details = business_platform_details

    @classmethod
    def from_dict(cls, dikt) -> 'BusinessPlatformDetailsObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BusinessPlatformDetailsObject of this BusinessPlatformDetailsObject.  # noqa: E501
        :rtype: BusinessPlatformDetailsObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def business_platform_details(self) -> BusinessPlatformDetails:
        """Gets the business_platform_details of this BusinessPlatformDetailsObject.


        :return: The business_platform_details of this BusinessPlatformDetailsObject.
        :rtype: BusinessPlatformDetails
        """
        return self._business_platform_details

    @business_platform_details.setter
    def business_platform_details(self, business_platform_details: BusinessPlatformDetails):
        """Sets the business_platform_details of this BusinessPlatformDetailsObject.


        :param business_platform_details: The business_platform_details of this BusinessPlatformDetailsObject.
        :type business_platform_details: BusinessPlatformDetails
        """

        self._business_platform_details = business_platform_details
