# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.business_bank_account_update import BusinessBankAccountUpdate  # noqa: F401,E501
from swagger_server import util


class BusinessBankAccountObjectUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, business_bank_account: BusinessBankAccountUpdate=None):  # noqa: E501
        """BusinessBankAccountObjectUpdate - a model defined in Swagger

        :param business_bank_account: The business_bank_account of this BusinessBankAccountObjectUpdate.  # noqa: E501
        :type business_bank_account: BusinessBankAccountUpdate
        """
        self.swagger_types = {
            'business_bank_account': BusinessBankAccountUpdate
        }

        self.attribute_map = {
            'business_bank_account': 'businessBankAccount'
        }

        self._business_bank_account = business_bank_account

    @classmethod
    def from_dict(cls, dikt) -> 'BusinessBankAccountObjectUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BusinessBankAccountObjectUpdate of this BusinessBankAccountObjectUpdate.  # noqa: E501
        :rtype: BusinessBankAccountObjectUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def business_bank_account(self) -> BusinessBankAccountUpdate:
        """Gets the business_bank_account of this BusinessBankAccountObjectUpdate.


        :return: The business_bank_account of this BusinessBankAccountObjectUpdate.
        :rtype: BusinessBankAccountUpdate
        """
        return self._business_bank_account

    @business_bank_account.setter
    def business_bank_account(self, business_bank_account: BusinessBankAccountUpdate):
        """Sets the business_bank_account of this BusinessBankAccountObjectUpdate.


        :param business_bank_account: The business_bank_account of this BusinessBankAccountObjectUpdate.
        :type business_bank_account: BusinessBankAccountUpdate
        """

        self._business_bank_account = business_bank_account
