# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.business_platform_update import BusinessPlatformUpdate  # noqa: F401,E501
from swagger_server import util


class BusinessPlatformObjectUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, business_platform: BusinessPlatformUpdate=None):  # noqa: E501
        """BusinessPlatformObjectUpdate - a model defined in Swagger

        :param business_platform: The business_platform of this BusinessPlatformObjectUpdate.  # noqa: E501
        :type business_platform: BusinessPlatformUpdate
        """
        self.swagger_types = {
            'business_platform': BusinessPlatformUpdate
        }

        self.attribute_map = {
            'business_platform': 'businessPlatform'
        }

        self._business_platform = business_platform

    @classmethod
    def from_dict(cls, dikt) -> 'BusinessPlatformObjectUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BusinessPlatformObjectUpdate of this BusinessPlatformObjectUpdate.  # noqa: E501
        :rtype: BusinessPlatformObjectUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def business_platform(self) -> BusinessPlatformUpdate:
        """Gets the business_platform of this BusinessPlatformObjectUpdate.


        :return: The business_platform of this BusinessPlatformObjectUpdate.
        :rtype: BusinessPlatformUpdate
        """
        return self._business_platform

    @business_platform.setter
    def business_platform(self, business_platform: BusinessPlatformUpdate):
        """Sets the business_platform of this BusinessPlatformObjectUpdate.


        :param business_platform: The business_platform of this BusinessPlatformObjectUpdate.
        :type business_platform: BusinessPlatformUpdate
        """

        self._business_platform = business_platform
