# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.business import Business  # noqa: F401,E501
from swagger_server import util


class BusinessObject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, business: Business=None):  # noqa: E501
        """BusinessObject - a model defined in Swagger

        :param business: The business of this BusinessObject.  # noqa: E501
        :type business: Business
        """
        self.swagger_types = {
            'business': Business
        }

        self.attribute_map = {
            'business': 'business'
        }

        self._business = business

    @classmethod
    def from_dict(cls, dikt) -> 'BusinessObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BusinessObject of this BusinessObject.  # noqa: E501
        :rtype: BusinessObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def business(self) -> Business:
        """Gets the business of this BusinessObject.


        :return: The business of this BusinessObject.
        :rtype: Business
        """
        return self._business

    @business.setter
    def business(self, business: Business):
        """Sets the business of this BusinessObject.


        :param business: The business of this BusinessObject.
        :type business: Business
        """

        self._business = business
