# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CitySummary(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, city_name: str=None, state_name: str=None, tin_number: int=None):  # noqa: E501
        """CitySummary - a model defined in Swagger

        :param id: The id of this CitySummary.  # noqa: E501
        :type id: str
        :param city_name: The city_name of this CitySummary.  # noqa: E501
        :type city_name: str
        :param state_name: The state_name of this CitySummary.  # noqa: E501
        :type state_name: str
        :param tin_number: The tin_number of this CitySummary.  # noqa: E501
        :type tin_number: int
        """
        self.swagger_types = {
            'id': str,
            'city_name': str,
            'state_name': str,
            'tin_number': int
        }

        self.attribute_map = {
            'id': '_id',
            'city_name': 'city_name',
            'state_name': 'state_name',
            'tin_number': 'tin_number'
        }

        self._id = id
        self._city_name = city_name
        self._state_name = state_name
        self._tin_number = tin_number

    @classmethod
    def from_dict(cls, dikt) -> 'CitySummary':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CitySummary of this CitySummary.  # noqa: E501
        :rtype: CitySummary
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this CitySummary.


        :return: The id of this CitySummary.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this CitySummary.


        :param id: The id of this CitySummary.
        :type id: str
        """

        self._id = id

    @property
    def city_name(self) -> str:
        """Gets the city_name of this CitySummary.


        :return: The city_name of this CitySummary.
        :rtype: str
        """
        return self._city_name

    @city_name.setter
    def city_name(self, city_name: str):
        """Sets the city_name of this CitySummary.


        :param city_name: The city_name of this CitySummary.
        :type city_name: str
        """

        self._city_name = city_name

    @property
    def state_name(self) -> str:
        """Gets the state_name of this CitySummary.


        :return: The state_name of this CitySummary.
        :rtype: str
        """
        return self._state_name

    @state_name.setter
    def state_name(self, state_name: str):
        """Sets the state_name of this CitySummary.


        :param state_name: The state_name of this CitySummary.
        :type state_name: str
        """

        self._state_name = state_name

    @property
    def tin_number(self) -> int:
        """Gets the tin_number of this CitySummary.


        :return: The tin_number of this CitySummary.
        :rtype: int
        """
        return self._tin_number

    @tin_number.setter
    def tin_number(self, tin_number: int):
        """Sets the tin_number of this CitySummary.


        :param tin_number: The tin_number of this CitySummary.
        :type tin_number: int
        """

        self._tin_number = tin_number
