# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class City(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, state_code: str=None, city_name: str=None):  # noqa: E501
        """City - a model defined in Swagger

        :param id: The id of this City.  # noqa: E501
        :type id: int
        :param state_code: The state_code of this City.  # noqa: E501
        :type state_code: str
        :param city_name: The city_name of this City.  # noqa: E501
        :type city_name: str
        """
        self.swagger_types = {
            'id': int,
            'state_code': str,
            'city_name': str
        }

        self.attribute_map = {
            'id': '_id',
            'state_code': 'state_code',
            'city_name': 'city_name'
        }

        self._id = id
        self._state_code = state_code
        self._city_name = city_name

    @classmethod
    def from_dict(cls, dikt) -> 'City':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The City of this City.  # noqa: E501
        :rtype: City
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this City.


        :return: The id of this City.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this City.


        :param id: The id of this City.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def state_code(self) -> str:
        """Gets the state_code of this City.


        :return: The state_code of this City.
        :rtype: str
        """
        return self._state_code

    @state_code.setter
    def state_code(self, state_code: str):
        """Sets the state_code of this City.


        :param state_code: The state_code of this City.
        :type state_code: str
        """
        if state_code is None:
            raise ValueError("Invalid value for `state_code`, must not be `None`")  # noqa: E501

        self._state_code = state_code

    @property
    def city_name(self) -> str:
        """Gets the city_name of this City.


        :return: The city_name of this City.
        :rtype: str
        """
        return self._city_name

    @city_name.setter
    def city_name(self, city_name: str):
        """Sets the city_name of this City.


        :param city_name: The city_name of this City.
        :type city_name: str
        """
        if city_name is None:
            raise ValueError("Invalid value for `city_name`, must not be `None`")  # noqa: E501

        self._city_name = city_name
