# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.documents import Documents  # noqa: F401,E501
from swagger_server import util


class DocumentsObject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, file: Documents=None):  # noqa: E501
        """DocumentsObject - a model defined in Swagger

        :param file: The file of this DocumentsObject.  # noqa: E501
        :type file: Documents
        """
        self.swagger_types = {
            'file': Documents
        }

        self.attribute_map = {
            'file': 'File'
        }

        self._file = file

    @classmethod
    def from_dict(cls, dikt) -> 'DocumentsObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DocumentsObject of this DocumentsObject.  # noqa: E501
        :rtype: DocumentsObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file(self) -> Documents:
        """Gets the file of this DocumentsObject.


        :return: The file of this DocumentsObject.
        :rtype: Documents
        """
        return self._file

    @file.setter
    def file(self, file: Documents):
        """Sets the file of this DocumentsObject.


        :param file: The file of this DocumentsObject.
        :type file: Documents
        """
        if file is None:
            raise ValueError("Invalid value for `file`, must not be `None`")  # noqa: E501

        self._file = file
