# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.loan_application_tasks import LoanApplicationTasks  # noqa: F401,E501
from swagger_server import util


class LoanApplicationTasksObject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, loan_app_tasks: LoanApplicationTasks=None):  # noqa: E501
        """LoanApplicationTasksObject - a model defined in Swagger

        :param loan_app_tasks: The loan_app_tasks of this LoanApplicationTasksObject.  # noqa: E501
        :type loan_app_tasks: LoanApplicationTasks
        """
        self.swagger_types = {
            'loan_app_tasks': LoanApplicationTasks
        }

        self.attribute_map = {
            'loan_app_tasks': 'loanAppTasks'
        }

        self._loan_app_tasks = loan_app_tasks

    @classmethod
    def from_dict(cls, dikt) -> 'LoanApplicationTasksObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoanApplicationTasksObject of this LoanApplicationTasksObject.  # noqa: E501
        :rtype: LoanApplicationTasksObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def loan_app_tasks(self) -> LoanApplicationTasks:
        """Gets the loan_app_tasks of this LoanApplicationTasksObject.


        :return: The loan_app_tasks of this LoanApplicationTasksObject.
        :rtype: LoanApplicationTasks
        """
        return self._loan_app_tasks

    @loan_app_tasks.setter
    def loan_app_tasks(self, loan_app_tasks: LoanApplicationTasks):
        """Sets the loan_app_tasks of this LoanApplicationTasksObject.


        :param loan_app_tasks: The loan_app_tasks of this LoanApplicationTasksObject.
        :type loan_app_tasks: LoanApplicationTasks
        """
        if loan_app_tasks is None:
            raise ValueError("Invalid value for `loan_app_tasks`, must not be `None`")  # noqa: E501

        self._loan_app_tasks = loan_app_tasks
