# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.loan_application_update import LoanApplicationUpdate  # noqa: F401,E501
from swagger_server import util


class LoanApplicationObjectUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, loan_application: LoanApplicationUpdate=None):  # noqa: E501
        """LoanApplicationObjectUpdate - a model defined in Swagger

        :param loan_application: The loan_application of this LoanApplicationObjectUpdate.  # noqa: E501
        :type loan_application: LoanApplicationUpdate
        """
        self.swagger_types = {
            'loan_application': LoanApplicationUpdate
        }

        self.attribute_map = {
            'loan_application': 'loanApplication'
        }

        self._loan_application = loan_application

    @classmethod
    def from_dict(cls, dikt) -> 'LoanApplicationObjectUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoanApplicationObjectUpdate of this LoanApplicationObjectUpdate.  # noqa: E501
        :rtype: LoanApplicationObjectUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def loan_application(self) -> LoanApplicationUpdate:
        """Gets the loan_application of this LoanApplicationObjectUpdate.


        :return: The loan_application of this LoanApplicationObjectUpdate.
        :rtype: LoanApplicationUpdate
        """
        return self._loan_application

    @loan_application.setter
    def loan_application(self, loan_application: LoanApplicationUpdate):
        """Sets the loan_application of this LoanApplicationObjectUpdate.


        :param loan_application: The loan_application of this LoanApplicationObjectUpdate.
        :type loan_application: LoanApplicationUpdate
        """
        if loan_application is None:
            raise ValueError("Invalid value for `loan_application`, must not be `None`")  # noqa: E501

        self._loan_application = loan_application
