# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.loan_application_documents import LoanApplicationDocuments  # noqa: F401,E501
from swagger_server import util


class LoanApplicationDocumentsArray(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, loan_app_docs: List[LoanApplicationDocuments]=None):  # noqa: E501
        """LoanApplicationDocumentsArray - a model defined in Swagger

        :param loan_app_docs: The loan_app_docs of this LoanApplicationDocumentsArray.  # noqa: E501
        :type loan_app_docs: List[LoanApplicationDocuments]
        """
        self.swagger_types = {
            'loan_app_docs': List[LoanApplicationDocuments]
        }

        self.attribute_map = {
            'loan_app_docs': 'loanAppDocs'
        }

        self._loan_app_docs = loan_app_docs

    @classmethod
    def from_dict(cls, dikt) -> 'LoanApplicationDocumentsArray':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoanApplicationDocumentsArray of this LoanApplicationDocumentsArray.  # noqa: E501
        :rtype: LoanApplicationDocumentsArray
        """
        return util.deserialize_model(dikt, cls)

    @property
    def loan_app_docs(self) -> List[LoanApplicationDocuments]:
        """Gets the loan_app_docs of this LoanApplicationDocumentsArray.


        :return: The loan_app_docs of this LoanApplicationDocumentsArray.
        :rtype: List[LoanApplicationDocuments]
        """
        return self._loan_app_docs

    @loan_app_docs.setter
    def loan_app_docs(self, loan_app_docs: List[LoanApplicationDocuments]):
        """Sets the loan_app_docs of this LoanApplicationDocumentsArray.


        :param loan_app_docs: The loan_app_docs of this LoanApplicationDocumentsArray.
        :type loan_app_docs: List[LoanApplicationDocuments]
        """
        if loan_app_docs is None:
            raise ValueError("Invalid value for `loan_app_docs`, must not be `None`")  # noqa: E501

        self._loan_app_docs = loan_app_docs
