# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.business_update import BusinessUpdate  # noqa: F401,E501
from swagger_server import util


class BusinessObjectUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, business: BusinessUpdate=None):  # noqa: E501
        """BusinessObjectUpdate - a model defined in Swagger

        :param business: The business of this BusinessObjectUpdate.  # noqa: E501
        :type business: BusinessUpdate
        """
        self.swagger_types = {
            'business': BusinessUpdate
        }

        self.attribute_map = {
            'business': 'business'
        }

        self._business = business

    @classmethod
    def from_dict(cls, dikt) -> 'BusinessObjectUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BusinessObjectUpdate of this BusinessObjectUpdate.  # noqa: E501
        :rtype: BusinessObjectUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def business(self) -> BusinessUpdate:
        """Gets the business of this BusinessObjectUpdate.


        :return: The business of this BusinessObjectUpdate.
        :rtype: BusinessUpdate
        """
        return self._business

    @business.setter
    def business(self, business: BusinessUpdate):
        """Sets the business of this BusinessObjectUpdate.


        :param business: The business of this BusinessObjectUpdate.
        :type business: BusinessUpdate
        """

        self._business = business
