# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.business_address_update import BusinessAddressUpdate  # noqa: F401,E501
from swagger_server import util


class BusinessAddressObjectUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, business_address: BusinessAddressUpdate=None):  # noqa: E501
        """BusinessAddressObjectUpdate - a model defined in Swagger

        :param business_address: The business_address of this BusinessAddressObjectUpdate.  # noqa: E501
        :type business_address: BusinessAddressUpdate
        """
        self.swagger_types = {
            'business_address': BusinessAddressUpdate
        }

        self.attribute_map = {
            'business_address': 'businessAddress'
        }

        self._business_address = business_address

    @classmethod
    def from_dict(cls, dikt) -> 'BusinessAddressObjectUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BusinessAddressObjectUpdate of this BusinessAddressObjectUpdate.  # noqa: E501
        :rtype: BusinessAddressObjectUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def business_address(self) -> BusinessAddressUpdate:
        """Gets the business_address of this BusinessAddressObjectUpdate.


        :return: The business_address of this BusinessAddressObjectUpdate.
        :rtype: BusinessAddressUpdate
        """
        return self._business_address

    @business_address.setter
    def business_address(self, business_address: BusinessAddressUpdate):
        """Sets the business_address of this BusinessAddressObjectUpdate.


        :param business_address: The business_address of this BusinessAddressObjectUpdate.
        :type business_address: BusinessAddressUpdate
        """
        if business_address is None:
            raise ValueError("Invalid value for `business_address`, must not be `None`")  # noqa: E501

        self._business_address = business_address
