# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.business_platform import BusinessPlatform  # noqa: F401,E501
from swagger_server import util


class BusinessPlatformObject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, business_platform: BusinessPlatform=None):  # noqa: E501
        """BusinessPlatformObject - a model defined in Swagger

        :param business_platform: The business_platform of this BusinessPlatformObject.  # noqa: E501
        :type business_platform: BusinessPlatform
        """
        self.swagger_types = {
            'business_platform': BusinessPlatform
        }

        self.attribute_map = {
            'business_platform': 'businessPlatform'
        }

        self._business_platform = business_platform

    @classmethod
    def from_dict(cls, dikt) -> 'BusinessPlatformObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BusinessPlatformObject of this BusinessPlatformObject.  # noqa: E501
        :rtype: BusinessPlatformObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def business_platform(self) -> BusinessPlatform:
        """Gets the business_platform of this BusinessPlatformObject.


        :return: The business_platform of this BusinessPlatformObject.
        :rtype: BusinessPlatform
        """
        return self._business_platform

    @business_platform.setter
    def business_platform(self, business_platform: BusinessPlatform):
        """Sets the business_platform of this BusinessPlatformObject.


        :param business_platform: The business_platform of this BusinessPlatformObject.
        :type business_platform: BusinessPlatform
        """

        self._business_platform = business_platform
