# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.business_platform_details_update import BusinessPlatformDetailsUpdate  # noqa: F401,E501
from swagger_server import util


class BusinessPlatformDetailsObjectUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, business_platform_details: BusinessPlatformDetailsUpdate=None):  # noqa: E501
        """BusinessPlatformDetailsObjectUpdate - a model defined in Swagger

        :param business_platform_details: The business_platform_details of this BusinessPlatformDetailsObjectUpdate.  # noqa: E501
        :type business_platform_details: BusinessPlatformDetailsUpdate
        """
        self.swagger_types = {
            'business_platform_details': BusinessPlatformDetailsUpdate
        }

        self.attribute_map = {
            'business_platform_details': 'businessPlatformDetails'
        }

        self._business_platform_details = business_platform_details

    @classmethod
    def from_dict(cls, dikt) -> 'BusinessPlatformDetailsObjectUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BusinessPlatformDetailsObjectUpdate of this BusinessPlatformDetailsObjectUpdate.  # noqa: E501
        :rtype: BusinessPlatformDetailsObjectUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def business_platform_details(self) -> BusinessPlatformDetailsUpdate:
        """Gets the business_platform_details of this BusinessPlatformDetailsObjectUpdate.


        :return: The business_platform_details of this BusinessPlatformDetailsObjectUpdate.
        :rtype: BusinessPlatformDetailsUpdate
        """
        return self._business_platform_details

    @business_platform_details.setter
    def business_platform_details(self, business_platform_details: BusinessPlatformDetailsUpdate):
        """Sets the business_platform_details of this BusinessPlatformDetailsObjectUpdate.


        :param business_platform_details: The business_platform_details of this BusinessPlatformDetailsObjectUpdate.
        :type business_platform_details: BusinessPlatformDetailsUpdate
        """

        self._business_platform_details = business_platform_details
