# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BusinessPlatformDetailsUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, total_amount: float=None):  # noqa: E501
        """BusinessPlatformDetailsUpdate - a model defined in Swagger

        :param total_amount: The total_amount of this BusinessPlatformDetailsUpdate.  # noqa: E501
        :type total_amount: float
        """
        self.swagger_types = {
            'total_amount': float
        }

        self.attribute_map = {
            'total_amount': 'total_amount'
        }

        self._total_amount = total_amount

    @classmethod
    def from_dict(cls, dikt) -> 'BusinessPlatformDetailsUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BusinessPlatformDetailsUpdate of this BusinessPlatformDetailsUpdate.  # noqa: E501
        :rtype: BusinessPlatformDetailsUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total_amount(self) -> float:
        """Gets the total_amount of this BusinessPlatformDetailsUpdate.


        :return: The total_amount of this BusinessPlatformDetailsUpdate.
        :rtype: float
        """
        return self._total_amount

    @total_amount.setter
    def total_amount(self, total_amount: float):
        """Sets the total_amount of this BusinessPlatformDetailsUpdate.


        :param total_amount: The total_amount of this BusinessPlatformDetailsUpdate.
        :type total_amount: float
        """

        self._total_amount = total_amount
