# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BusinessPlatform(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, version: int=None, org_name: str=None, merchant_id: str=None, operating_since_month: str=None, operating_since_year: int=None, last_six_months_amount: int=None):  # noqa: E501
        """BusinessPlatform - a model defined in Swagger

        :param version: The version of this BusinessPlatform.  # noqa: E501
        :type version: int
        :param org_name: The org_name of this BusinessPlatform.  # noqa: E501
        :type org_name: str
        :param merchant_id: The merchant_id of this BusinessPlatform.  # noqa: E501
        :type merchant_id: str
        :param operating_since_month: The operating_since_month of this BusinessPlatform.  # noqa: E501
        :type operating_since_month: str
        :param operating_since_year: The operating_since_year of this BusinessPlatform.  # noqa: E501
        :type operating_since_year: int
        :param last_six_months_amount: The last_six_months_amount of this BusinessPlatform.  # noqa: E501
        :type last_six_months_amount: int
        """
        self.swagger_types = {
            'version': int,
            'org_name': str,
            'merchant_id': str,
            'operating_since_month': str,
            'operating_since_year': int,
            'last_six_months_amount': int
        }

        self.attribute_map = {
            'version': 'version',
            'org_name': 'org_name',
            'merchant_id': 'merchant_id',
            'operating_since_month': 'operating_since_month',
            'operating_since_year': 'operating_since_year',
            'last_six_months_amount': 'last_six_months_amount'
        }

        self._version = version
        self._org_name = org_name
        self._merchant_id = merchant_id
        self._operating_since_month = operating_since_month
        self._operating_since_year = operating_since_year
        self._last_six_months_amount = last_six_months_amount

    @classmethod
    def from_dict(cls, dikt) -> 'BusinessPlatform':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BusinessPlatform of this BusinessPlatform.  # noqa: E501
        :rtype: BusinessPlatform
        """
        return util.deserialize_model(dikt, cls)

    @property
    def version(self) -> int:
        """Gets the version of this BusinessPlatform.


        :return: The version of this BusinessPlatform.
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version: int):
        """Sets the version of this BusinessPlatform.


        :param version: The version of this BusinessPlatform.
        :type version: int
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version

    @property
    def org_name(self) -> str:
        """Gets the org_name of this BusinessPlatform.


        :return: The org_name of this BusinessPlatform.
        :rtype: str
        """
        return self._org_name

    @org_name.setter
    def org_name(self, org_name: str):
        """Sets the org_name of this BusinessPlatform.


        :param org_name: The org_name of this BusinessPlatform.
        :type org_name: str
        """
        if org_name is None:
            raise ValueError("Invalid value for `org_name`, must not be `None`")  # noqa: E501

        self._org_name = org_name

    @property
    def merchant_id(self) -> str:
        """Gets the merchant_id of this BusinessPlatform.


        :return: The merchant_id of this BusinessPlatform.
        :rtype: str
        """
        return self._merchant_id

    @merchant_id.setter
    def merchant_id(self, merchant_id: str):
        """Sets the merchant_id of this BusinessPlatform.


        :param merchant_id: The merchant_id of this BusinessPlatform.
        :type merchant_id: str
        """
        if merchant_id is None:
            raise ValueError("Invalid value for `merchant_id`, must not be `None`")  # noqa: E501

        self._merchant_id = merchant_id

    @property
    def operating_since_month(self) -> str:
        """Gets the operating_since_month of this BusinessPlatform.


        :return: The operating_since_month of this BusinessPlatform.
        :rtype: str
        """
        return self._operating_since_month

    @operating_since_month.setter
    def operating_since_month(self, operating_since_month: str):
        """Sets the operating_since_month of this BusinessPlatform.


        :param operating_since_month: The operating_since_month of this BusinessPlatform.
        :type operating_since_month: str
        """
        if operating_since_month is None:
            raise ValueError("Invalid value for `operating_since_month`, must not be `None`")  # noqa: E501

        self._operating_since_month = operating_since_month

    @property
    def operating_since_year(self) -> int:
        """Gets the operating_since_year of this BusinessPlatform.


        :return: The operating_since_year of this BusinessPlatform.
        :rtype: int
        """
        return self._operating_since_year

    @operating_since_year.setter
    def operating_since_year(self, operating_since_year: int):
        """Sets the operating_since_year of this BusinessPlatform.


        :param operating_since_year: The operating_since_year of this BusinessPlatform.
        :type operating_since_year: int
        """
        if operating_since_year is None:
            raise ValueError("Invalid value for `operating_since_year`, must not be `None`")  # noqa: E501
        if operating_since_year is not None and operating_since_year < 2000:  # noqa: E501
            raise ValueError("Invalid value for `operating_since_year`, must be a value greater than or equal to `2000`")  # noqa: E501

        self._operating_since_year = operating_since_year

    @property
    def last_six_months_amount(self) -> int:
        """Gets the last_six_months_amount of this BusinessPlatform.


        :return: The last_six_months_amount of this BusinessPlatform.
        :rtype: int
        """
        return self._last_six_months_amount

    @last_six_months_amount.setter
    def last_six_months_amount(self, last_six_months_amount: int):
        """Sets the last_six_months_amount of this BusinessPlatform.


        :param last_six_months_amount: The last_six_months_amount of this BusinessPlatform.
        :type last_six_months_amount: int
        """
        if last_six_months_amount is None:
            raise ValueError("Invalid value for `last_six_months_amount`, must not be `None`")  # noqa: E501

        self._last_six_months_amount = last_six_months_amount
