# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BusinessSubCategory(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, business_sub_cat_code: str=None, business_sub_cat_desc: str=None):  # noqa: E501
        """BusinessSubCategory - a model defined in Swagger

        :param id: The id of this BusinessSubCategory.  # noqa: E501
        :type id: str
        :param business_sub_cat_code: The business_sub_cat_code of this BusinessSubCategory.  # noqa: E501
        :type business_sub_cat_code: str
        :param business_sub_cat_desc: The business_sub_cat_desc of this BusinessSubCategory.  # noqa: E501
        :type business_sub_cat_desc: str
        """
        self.swagger_types = {
            'id': str,
            'business_sub_cat_code': str,
            'business_sub_cat_desc': str
        }

        self.attribute_map = {
            'id': '_id',
            'business_sub_cat_code': 'business_sub_cat_code',
            'business_sub_cat_desc': 'business_sub_cat_desc'
        }

        self._id = id
        self._business_sub_cat_code = business_sub_cat_code
        self._business_sub_cat_desc = business_sub_cat_desc

    @classmethod
    def from_dict(cls, dikt) -> 'BusinessSubCategory':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BusinessSubCategory of this BusinessSubCategory.  # noqa: E501
        :rtype: BusinessSubCategory
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this BusinessSubCategory.


        :return: The id of this BusinessSubCategory.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this BusinessSubCategory.


        :param id: The id of this BusinessSubCategory.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def business_sub_cat_code(self) -> str:
        """Gets the business_sub_cat_code of this BusinessSubCategory.


        :return: The business_sub_cat_code of this BusinessSubCategory.
        :rtype: str
        """
        return self._business_sub_cat_code

    @business_sub_cat_code.setter
    def business_sub_cat_code(self, business_sub_cat_code: str):
        """Sets the business_sub_cat_code of this BusinessSubCategory.


        :param business_sub_cat_code: The business_sub_cat_code of this BusinessSubCategory.
        :type business_sub_cat_code: str
        """
        if business_sub_cat_code is None:
            raise ValueError("Invalid value for `business_sub_cat_code`, must not be `None`")  # noqa: E501

        self._business_sub_cat_code = business_sub_cat_code

    @property
    def business_sub_cat_desc(self) -> str:
        """Gets the business_sub_cat_desc of this BusinessSubCategory.


        :return: The business_sub_cat_desc of this BusinessSubCategory.
        :rtype: str
        """
        return self._business_sub_cat_desc

    @business_sub_cat_desc.setter
    def business_sub_cat_desc(self, business_sub_cat_desc: str):
        """Sets the business_sub_cat_desc of this BusinessSubCategory.


        :param business_sub_cat_desc: The business_sub_cat_desc of this BusinessSubCategory.
        :type business_sub_cat_desc: str
        """
        if business_sub_cat_desc is None:
            raise ValueError("Invalid value for `business_sub_cat_desc`, must not be `None`")  # noqa: E501

        self._business_sub_cat_desc = business_sub_cat_desc
