# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.error import Error  # noqa: F401,E501
from swagger_server import util


class ErrorObject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, error: Error=None):  # noqa: E501
        """ErrorObject - a model defined in Swagger

        :param error: The error of this ErrorObject.  # noqa: E501
        :type error: Error
        """
        self.swagger_types = {
            'error': Error
        }

        self.attribute_map = {
            'error': 'error'
        }

        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErrorObject of this ErrorObject.  # noqa: E501
        :rtype: ErrorObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self) -> Error:
        """Gets the error of this ErrorObject.


        :return: The error of this ErrorObject.
        :rtype: Error
        """
        return self._error

    @error.setter
    def error(self, error: Error):
        """Sets the error of this ErrorObject.


        :param error: The error of this ErrorObject.
        :type error: Error
        """
        if error is None:
            raise ValueError("Invalid value for `error`, must not be `None`")  # noqa: E501

        self._error = error
