# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.individual import Individual  # noqa: F401,E501
from swagger_server import util


class IndividualObject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, individual: Individual=None):  # noqa: E501
        """IndividualObject - a model defined in Swagger

        :param individual: The individual of this IndividualObject.  # noqa: E501
        :type individual: Individual
        """
        self.swagger_types = {
            'individual': Individual
        }

        self.attribute_map = {
            'individual': 'individual'
        }

        self._individual = individual

    @classmethod
    def from_dict(cls, dikt) -> 'IndividualObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IndividualObject of this IndividualObject.  # noqa: E501
        :rtype: IndividualObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def individual(self) -> Individual:
        """Gets the individual of this IndividualObject.


        :return: The individual of this IndividualObject.
        :rtype: Individual
        """
        return self._individual

    @individual.setter
    def individual(self, individual: Individual):
        """Sets the individual of this IndividualObject.


        :param individual: The individual of this IndividualObject.
        :type individual: Individual
        """

        self._individual = individual
