# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LoanApplicationUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, version: int=None, business_pan: str=None, business_name: str=None, loan_amount_required: float=None, currency: str='INR'):  # noqa: E501
        """LoanApplicationUpdate - a model defined in Swagger

        :param id: The id of this LoanApplicationUpdate.  # noqa: E501
        :type id: str
        :param version: The version of this LoanApplicationUpdate.  # noqa: E501
        :type version: int
        :param business_pan: The business_pan of this LoanApplicationUpdate.  # noqa: E501
        :type business_pan: str
        :param business_name: The business_name of this LoanApplicationUpdate.  # noqa: E501
        :type business_name: str
        :param loan_amount_required: The loan_amount_required of this LoanApplicationUpdate.  # noqa: E501
        :type loan_amount_required: float
        :param currency: The currency of this LoanApplicationUpdate.  # noqa: E501
        :type currency: str
        """
        self.swagger_types = {
            'id': str,
            'version': int,
            'business_pan': str,
            'business_name': str,
            'loan_amount_required': float,
            'currency': str
        }

        self.attribute_map = {
            'id': '_id',
            'version': 'version',
            'business_pan': 'business_pan',
            'business_name': 'business_name',
            'loan_amount_required': 'loan_amount_required',
            'currency': 'currency'
        }

        self._id = id
        self._version = version
        self._business_pan = business_pan
        self._business_name = business_name
        self._loan_amount_required = loan_amount_required
        self._currency = currency

    @classmethod
    def from_dict(cls, dikt) -> 'LoanApplicationUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoanApplicationUpdate of this LoanApplicationUpdate.  # noqa: E501
        :rtype: LoanApplicationUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this LoanApplicationUpdate.


        :return: The id of this LoanApplicationUpdate.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this LoanApplicationUpdate.


        :param id: The id of this LoanApplicationUpdate.
        :type id: str
        """

        self._id = id

    @property
    def version(self) -> int:
        """Gets the version of this LoanApplicationUpdate.


        :return: The version of this LoanApplicationUpdate.
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version: int):
        """Sets the version of this LoanApplicationUpdate.


        :param version: The version of this LoanApplicationUpdate.
        :type version: int
        """

        self._version = version

    @property
    def business_pan(self) -> str:
        """Gets the business_pan of this LoanApplicationUpdate.


        :return: The business_pan of this LoanApplicationUpdate.
        :rtype: str
        """
        return self._business_pan

    @business_pan.setter
    def business_pan(self, business_pan: str):
        """Sets the business_pan of this LoanApplicationUpdate.


        :param business_pan: The business_pan of this LoanApplicationUpdate.
        :type business_pan: str
        """

        self._business_pan = business_pan

    @property
    def business_name(self) -> str:
        """Gets the business_name of this LoanApplicationUpdate.


        :return: The business_name of this LoanApplicationUpdate.
        :rtype: str
        """
        return self._business_name

    @business_name.setter
    def business_name(self, business_name: str):
        """Sets the business_name of this LoanApplicationUpdate.


        :param business_name: The business_name of this LoanApplicationUpdate.
        :type business_name: str
        """

        self._business_name = business_name

    @property
    def loan_amount_required(self) -> float:
        """Gets the loan_amount_required of this LoanApplicationUpdate.


        :return: The loan_amount_required of this LoanApplicationUpdate.
        :rtype: float
        """
        return self._loan_amount_required

    @loan_amount_required.setter
    def loan_amount_required(self, loan_amount_required: float):
        """Sets the loan_amount_required of this LoanApplicationUpdate.


        :param loan_amount_required: The loan_amount_required of this LoanApplicationUpdate.
        :type loan_amount_required: float
        """
        if loan_amount_required is None:
            raise ValueError("Invalid value for `loan_amount_required`, must not be `None`")  # noqa: E501
        if loan_amount_required is not None and loan_amount_required > 1.0E+7:  # noqa: E501
            raise ValueError("Invalid value for `loan_amount_required`, must be a value less than or equal to `1.0E+7`")  # noqa: E501
        if loan_amount_required is not None and loan_amount_required < 1:  # noqa: E501
            raise ValueError("Invalid value for `loan_amount_required`, must be a value greater than or equal to `1`")  # noqa: E501

        self._loan_amount_required = loan_amount_required

    @property
    def currency(self) -> str:
        """Gets the currency of this LoanApplicationUpdate.


        :return: The currency of this LoanApplicationUpdate.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency: str):
        """Sets the currency of this LoanApplicationUpdate.


        :param currency: The currency of this LoanApplicationUpdate.
        :type currency: str
        """
        allowed_values = ["INR"]  # noqa: E501
        if currency not in allowed_values:
            raise ValueError(
                "Invalid value for `currency` ({0}), must be one of {1}"
                .format(currency, allowed_values)
            )

        self._currency = currency
