# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.loan_application import LoanApplication  # noqa: F401,E501
from swagger_server import util


class LoanApplicationObject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, loan_application: LoanApplication=None):  # noqa: E501
        """LoanApplicationObject - a model defined in Swagger

        :param loan_application: The loan_application of this LoanApplicationObject.  # noqa: E501
        :type loan_application: LoanApplication
        """
        self.swagger_types = {
            'loan_application': LoanApplication
        }

        self.attribute_map = {
            'loan_application': 'loanApplication'
        }

        self._loan_application = loan_application

    @classmethod
    def from_dict(cls, dikt) -> 'LoanApplicationObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoanApplicationObject of this LoanApplicationObject.  # noqa: E501
        :rtype: LoanApplicationObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def loan_application(self) -> LoanApplication:
        """Gets the loan_application of this LoanApplicationObject.


        :return: The loan_application of this LoanApplicationObject.
        :rtype: LoanApplication
        """
        return self._loan_application

    @loan_application.setter
    def loan_application(self, loan_application: LoanApplication):
        """Sets the loan_application of this LoanApplicationObject.


        :param loan_application: The loan_application of this LoanApplicationObject.
        :type loan_application: LoanApplication
        """
        if loan_application is None:
            raise ValueError("Invalid value for `loan_application`, must not be `None`")  # noqa: E501

        self._loan_application = loan_application
